import{a as P,i as a,S}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();let p=1;const b=15,v="https://pixabay.com/api/",w="47376974-17318822de3408abf70e5a971";async function u(t){try{return(await P(v,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:p,per_page:b}})).data}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}}async function g(){p+=1}async function E(){p=1}function f(t){return t.map(({webformatURL:r,largeImageURL:n,tags:s,likes:e,views:o,comments:i,downloads:L})=>`
   <a class="gallery-item" href="${n}">
   <div class=all-gallary>
   <img src="${r}" alt="${s}">
   <div class="description">
   <p>Likes: <span>"${e}"</span></p>
   <p>Views: <span>"${o}"</span></p>
   <p>Comments: <span>"${i}"</span></p>
   <p>Downloads: <span>"${L}"</span></p>
   </div>
   </div>
   </a>
    `).join("")}function q(t){t.innerHTML=""}function R(t){t.style.display="block"}function $(t){t.style.display="none"}const y=document.querySelector(".form-search"),c=document.querySelector(".gallery"),d=document.querySelector(".loader"),l=document.querySelector(".js-load-more");y.addEventListener("submit",h);l.addEventListener("click",g);let m=new S(".gallery-item",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250});y.addEventListener("submit",h);l.addEventListener("click",M);async function h(t){t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}q(c),R(d),E();try{const n=await u(r);if(!n.hits.length){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c.innerHTML=f(n.hits),m.refresh(),l.style.display="block"}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{$(d)}}async function M(){g();const t=document.querySelector(".input-form").value.trim();try{const r=await u(t);c.insertAdjacentHTML("beforeend",f(r.hits)),m.refresh(),page*perPage>=r.totalHits&&(l.style.display="none",a.info({message:"You've reached the end of search results.",position:"topRight"}));const n=c.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Error fetching more images!",position:"topRight"})}}
//# sourceMappingURL=index.js.map
